on:
  push:
    branches:
      - master
    paths:
      - 'charts/keycloak/**'
  workflow_dispatch:
jobs:
  callWorkflow:
    uses: mircohaug/helm-charts/.github/workflows/release-chart.yaml@master
    with:
      chart: keycloak
