name: Release charts
on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'charts/**'
  schedule:
    # every friday at 4 o'clock
    - cron: '0 16 * * 5'
  workflow_dispatch:
jobs:
  keycloak:
    uses: ./.github/workflows/release-chart-base.yaml
    with:
      chart: keycloak
  mailhog:
    needs:
      - keycloak
    uses: ./.github/workflows/release-chart-base.yaml
    with:
      chart: mailhog
