name: Release Keycloak chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
  workflow_dispatch:
jobs:
  release:
    uses: mircohaug/helm-charts/.github/workflows/release-chart.yaml@master
    with:
      chart: keycloak
  mailhog:
    uses: mircohaug/helm-charts/.github/workflows/release-chart.yaml@master
    with:
      chart: mailhof
