name: Release charts
on:
  push:
    branches:
      - master
#    paths:
#      - 'charts/**'
  schedule:
    # every friday at 4 o'clock
    - cron: '0 16 * * 5'
  workflow_dispatch:
jobs:
  doUpdate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: update keycloak
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: keycloak
    - name: find out what happend
      run: |
        ls -a
        git status
        git log -n 5
