name: Release charts
on:
  schedule:
    # each hour
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  keycloak:
    uses: mircohaug/helm-charts/.github/workflows/release-chart-base.yaml.yaml@master
    with:
      chart: keycloak
  mailhog:
    needs:
      - keycloak
    uses: mircohaug/helm-charts/.github/workflows/release-chart-base.yaml@master
    with:
      chart: mailhog
