name: Release charts
on:
  push:
    branches:
      - master
#    paths:
#      - 'charts/**'
  schedule:
    # every friday at 4 o'clock
    - cron: '0 16 * * 5'
  workflow_dispatch:
jobs:
  doUpdate:
    runs-on: ubuntu-latest
    steps:
    - name: update keycloak
      uses: ./.github/actions/bumpVersionAction
      with:
        chart: keycloak
